### PR TITLE
Various positioning and centering tests for investigating questions r…

### PR DESCRIPTION
**Pull request by hallvors**
…aised in forum thread 2291

### CODE REVIEW

**Comment by hallvors** [comment]
Two of these files do not output what I'd expect, something to do with max-height. I need a second opinion..

margin-auto-replaced-element-max-height-001.htm
table-cell-vertical-align-middle-centers-vertically-002.htm

Both these crop rather than scale the blue rectangle. Are the expectations wrong and Prince's behaviour correct, or vice versa?

**Comment by prjnt** [comment]
For margin-auto-replaced-element-max-height-001.htm, your "100% of what?" comment is on the money: the containing block of the associated box has height:auto, so http://www.w3.org/TR/CSS21/visudet.html#x16 says that max-height here is equivalent to max-height:none.

[Health warning: Please keep forehead away from hard surfaces while reading the following.]

table-cell-vertical-align-middle-centers-vertically-002.htm is actually the same, but for non-obvious reasons: in CSS, "The table cell's 'height' property can influence the height of the row, but it does not increase the height of the cell box" (fourth para of http://www.w3.org/TR/CSS21/tables.html#height-layout).  So the cell's height is actually effectively 'auto', even though it has 'height' of non-auto.  So there's no way of making a chain of percentages work through tables.

[Also, note that img is actually display:inline, so it has an implicit anonymous block box around it per visuren.html §9.2.1.1, which again has height:auto.  You could fix that with img{display:block}, but you'd still need it not to be in a table to get a percentage of page height.]

**Comment by prjnt** [comment]
Here's a simpler example of the phenomenon, avoiding replaced elements:

<table><tr>
<td style="height:2in; background:yellow">2in cell</td>
<td style="height:1in; background:yellow">
 1in cell
 <div style="height:50%; background:cyan">50%-height cyan box</div>
</td>
</tr></table>

Prince renders the cyan box as if height:auto, as per the above interpretation of cell box height being effectively 'auto'; Chromium renders it as approx 1in high; Firefox reders it as approx 0.5in high.

It might also be relevant that the language in visudet.html regarding ignoring percentages when containing height isn't a definite length was added very late in the CSS 2 process, and the language used was both ambiguous and contradictory.

**Comment by prjnt** [comment]
Also relevant to table-cell-vertical-align-middle-centers-vertically-002.htm (where the cell 'height' is not 1in but 100%) is that "CSS 2.1 does not define how the height of table cells and table rows is calculated when their height is specified using percentage values" (same section of tables.html).

The sentence before the "influence" sentence is "In CSS 2.1, the height of a cell box is the minimum height required by the content", and the wording of the condition for percentage max-height being treated as 'none' is "If the height of the containing block is not specified explicitly (i.e., it depends on content height)".  Since tables.html says that the cell height "is the minimum height required by the content", it does indeed "depend on content height"; so Prince's behaviour for the cyan box does seem the correct one per the spec here.

**Comment by hallvors** [comment]
Thanks a lot @prjnt . I'll simply fix the text describing expectations (although it seems this specific part of the CSS spec is a health hazard for web developers' foreheads..). Perhaps I'll also experiment a bit more with tests enforcing explicit heights on some or all ancestors, but I think the use cases and questions in the related forum threads are well handled by combinations of background-size and background-position, so it's not that important to make this work. Also, when we support vw and vh units we'll have new and potentially easier ways to scale content vertically in relation to page size.

**Comment by hallvors** [comment]
Actually I've found a couple of CSS fixes that means we get the intended effect.
margin-auto-replaced-element-max-height-001.htm : setting display:block and explicit 148mm height for the chapter element makes the max-height effective.

**Comment by hallvors** [comment]
For the more complex display:table-cell test, it works OK to set max-height to a hard-coded value on the img itself (although it also needs to be changed to inline-block to make that change have any effect..)

**Pull request merged**
